server:
  port: 8089

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-db:5432/ecommerce?currentSchema=${DB_SCHEMA:notification_service_uat}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:notification_service_uat}
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db/changelog-master.yaml
    default-schema: notification_service_uat
    liquibase-schema: notification_service_uat


  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    protocol: smtp

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

        debug: true


  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        include:
          headers: "*"

    listener:
      ack-mode: record



