server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:mem:notificationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true

  liquibase:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092

    listener:
      auto-startup: false
      ack-mode: record


  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        debug: true

logging:
  level:
    org.hibernate.SQL: DEBUG