spring:
  application:
    name: notification-service

  mail:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    listener:
      ack-mode: record

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

notification:
   system-email: ${SYSTEM_USER}
   retry-count: 3